### PR TITLE
feat: remove unsed locales

### LINKED ISSUE #54: Treeshaking of Locales
Hi, if I describe locales in nuxt.config.js file, it seems that all locales are included in the build file. But if no locales are defined, the output is tiny as expected. 

You can see it on the screenshots below. I got them via `yarn nuxt build --analyze`

### No locales included in nuxt.config.js: 

image

### locales included as `locales: "en-US"`:

image
 

How can we avoid this to make output smaller?

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
Resolve #54

### CODE REVIEW

**Comment by ChangJoo-Park** [comment]
It doesn't treeshake locale 😭 

image

**Comment by ChangJoo-Park** [comment]
latest version of date-fns has treeshaking probelm. Do you know https://github.com/date-fns/date-fns/issues/2207 ?

**Comment by ricardogobbosouza** [comment]
Hi @ChangJoo-Park 
Please try again
Its works now

**Comment by ricardogobbosouza** [comment]
Hi @ChangJoo-Park 
Please try again
Its works now 😄

**Comment by ricardogobbosouza** [comment]
Hi @ChangJoo-Park 
Please try again
Its works now 😄

**Comment by ChangJoo-Park** [comment]
It works!

image

**Pull request merged**
